---
- name: Ensure data directory is present.
  ansible.builtin.file:
    path: "{{ vault_data_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ vault_data_directory_user }}"
    group: "{{ vault_data_directory_group }}"
  when: ansible_hostname in groups['vault_servers']

- name: Ensure log directory is present.
  ansible.builtin.file:
    path: "{{ vault_log_directory }}"
    state: directory
    mode: '0755'
    owner: "{{ vault_log_directory_user }}"
    group: "{{ vault_log_directory_group }}"
  when: ansible_hostname in groups['vault_servers']
