---
bootstrap_location: "/home/{{ ansible_env.SUDO_USER }}/bootstrap-tokens"
hashicorp_datacenter_name: "velp"

consul_binary: "/usr/bin/consul"
consul_etc_directory: "/etc/consul.d"
consul_data_directory: "/opt/consul"
consul_data_directory_owner: "consul"
consul_data_directory_group: "consul"
consul_service_name: "consul"
consul_systemd_service_file: "/etc/systemd/system/consul.service"

consul_enable_syslog: "true"
consul_log_level: "info"
consul_log_json: "false"
consul_log_directory: "/var/log/consul"
consul_log_directory_owner: "consul"
consul_log_directory_group: "consul"
consul_log_rotate_duration: "86400s"
consul_log_rotate_max_files: "7"

consul_pause_seconds: "60"

consul_tls_ca_certificate_days: "3650"
consul_tls_server_certificate_days: "1827"
consul_tls_client_certificate_days: "1827"

consul_bootstrapped_true_file: "{{ consul_data_directory }}/bootstrapped.true"
consul_bootstrap_token_local_path: "{{ bootstrap_location }}/management.consul.token"

consul_cni_plugin_url: "https://github.com/containernetworking/plugins/releases/download/v1.0.1/cni-plugins-linux-amd64-v1.0.1.tgz"
consul_cni_target_directory: "/opt/cni/bin"
consul_cni_sysctl_settings:
  - key: "net.bridge.bridge-nf-call-arptables"
    value: "1"
  - key: "net.bridge.bridge-nf-call-ip6tables"
    value: "1"
  - key: "net.bridge.bridge-nf-call-iptables"
    value: "1"
consul_cni_sysctl_dest_file: "/etc/sysctl.d/20-consul-service-mesh.conf"

consul_agent_policy_file_name: "consul-agent-policy.hcl"
consul_agent_policy_file_local: "files/{{ consul_agent_policy_file_name }}"
consul_agent_policy_file_remote: "{{ consul_data_directory }}/{{ consul_agent_policy_file_name }}"
consul_agent_policy_name: "consul-agent"
consul_agent_policy_description: "Token for Consul Agents"
consul_agent_token_local_path: "{{ bootstrap_location }}/agent.consul.token"

consul_dns_policy_file_name: "dns-request-policy.hcl"
consul_dns_policy_file_local: "files/{{ consul_dns_policy_file_name }}"
consul_dns_policy_file_remote: "{{ consul_data_directory }}/{{ consul_dns_policy_file_name }}"
consul_dns_policy_name: "dns-requests"
consul_dns_policy_description: "Token for DNS Requests"
consul_dns_token_local_path: "{{ bootstrap_location }}/dns-requests.consul.token"

consul_snapshot_policy_file_name: "consul-snapshot-policy.hcl"
consul_snapshot_policy_file_local: "files/{{ consul_snapshot_policy_file_name }}"
consul_snapshot_policy_file_remote: "{{ consul_data_directory }}/{{ consul_snapshot_policy_file_name }}"
consul_snapshot_policy_name: "snapshot"
consul_snapshot_policy_description: "Token for snapshots"
consul_snapshot_token_local_path: "{{ bootstrap_location }}/snapshot.consul.token"

consul_snapshot_backup_main: "/srv/consul"
consul_snapshot_backup_location: "/srv/consul/backups"
consul_snapshot_backup_location_owner: "consul"
consul_snapshot_backup_location_group: "consul"
consul_snapshot_batchfile_template: "consul-snapshot.sh.j2"
consul_snapshot_batchfile_location: "/srv/consul/consul-snapshot.sh"
consul_snapshot_keep_days: "7"
consul_snapshot_filename: "consul"
consul_snapshot_file_extension: "snap"

consul_kv_backup_location: "{{ consul_snapshot_backup_location }}"
consul_kv_keep_days: "7"
consul_kv_filename: "consul_vault_kv"
consul_kv_file_extension: "json"
consul_kv_path: "vault/"

consul_snapshot_cron_backup_minute: "00"
consul_snapshot_cron_backup_hour: "00"
