---
bootstrap_location: "/home/{{ ansible_env.SUDO_USER }}/bootstrap-tokens"
datacenter_name: "velp"

vault_binary: "/usr/bin/vault"
vault_etc_directory: "/etc/vault.d"
vault_data_directory: "/opt/vault/data"
vault_data_directory_user: "vault"
vault_data_directory_group: "vault"
vault_tls_directory: "/opt/vault/tls"
vault_service_name: "vault"
vault_service_user: "vault"
vault_service_group: "vault"
vault_systemd_service_file: "/etc/systemd/system/vault.service"

vault_syslog_tag: "vault"
vault_syslog_facility: "AUTH"
vault_log_filename: "audit.log"
vault_log_directory: "/var/log/vault"
vault_log_location: "{{ vault_log_directory }}/{{ vault_log_filename }}"
vault_log_template_local: "vault.logrotate.j2"
vault_log_rotate_dir: "/etc/logrotate.d"
vault_log_rotate_filename: "vault"
vault_log_rotate_count: "7"
vault_log_rotation_interval: "daily"
vault_log_extension: "log"
vault_log_dateformat: "%Y-%m-%d."
vault_log_directory_user: "vault"
vault_log_directory_group: "vault"

vault_address: "https://127.0.0.1:8200"

vault_bootstrapped_true_file: "{{ vault_data_directory }}/bootstrapped.true"
vault_bootstrap_token_local_path: "{{ bootstrap_location }}/vault.consul.token"
vault_bootstrap_init_local_path: "{{ bootstrap_location }}/vault.master.keys"
vault_bootstrap_root_token_local_path: "{{ bootstrap_location }}/management.vault.token"
vault_bootstrap_root_true_file: "{{ vault_data_directory }}/second_root_token.true"

vault_ssl_cert_filename: "vault-cert.pem"
vault_ssl_key_filename: "vault-key.pem"
vault_ssl_ca_filename: "vault-ca.pem"
vault_ssl_ca_key_filename: "vault-ca-key.pem"
vault_ssl_ca_share_filename: "InThePicture_CA_Root.crt"

vault_ssl_base_path: "/opt/vault/tls"
vault_ssl_cert_dest: "{{ vault_ssl_base_path }}/{{ vault_ssl_cert_filename }}"
vault_ssl_key_dest: "{{ vault_ssl_base_path }}/{{ vault_ssl_key_filename }}"
vault_ssl_ca_dest: "{{ vault_ssl_base_path }}/{{ vault_ssl_ca_filename }}"
vault_ssl_ca_key_dest: "{{ vault_ssl_base_path }}/{{ vault_ssl_ca_key_filename }}"

vault_ssl_ca_common_name: "In The Picture Root CA"
vault_ssl_server_common_name: "vault.service.inthepicture.photo"
vault_ssl_server_subject_alt_names:
  - "DNS:{{ vault_ssl_server_common_name }}"
  - "DNS:active.vault.service.{{ consul_domain }}"
  - "DNS:standby.vault.service.{{ consul_domain }}"
  - "DNS:*.vault.service.{{ consul_domain }}"
  - "DNS:vault.service.{{ datacenter_name }}.{{ consul_domain }}"
  - "DNS:active.vault.service.{{ datacenter_name }}.{{ consul_domain }}"
  - "DNS:standby.vault.service.{{ datacenter_name }}.{{ consul_domain }}"
  - "DNS:*.vault.service.{{ datacenter_name }}.{{ consul_domain }}"
  - "DNS:*.node.{{ consul_domain }}"
  - "DNS:*.node.{{ datacenter_name }}.{{ consul_domain }}"
  - "IP:127.0.0.1"

vault_service_policy_file_name: "consul-vault-service-policy.hcl"
vault_service_policy_file_local: "files/{{ vault_service_policy_file_name }}"
vault_service_policy_file_remote: "{{ vault_data_directory }}/{{ vault_service_policy_file_name }}"
vault_consul_service_name: "vault-service"
vault_consul_service_description: "Vault Service Token"

vault_admin_policy_name: "pol-admin"
vault_admin_group_name: "grp-admin"
vault_admin_username: "atcomputing"
vault_admin_local_path: "{{ bootstrap_location }}/{{ vault_admin_username }}.vault.password"

vault_pki_int_path: "pki_int"
vault_pki_int_common_name: "In The Picture Intermediate CA"
vault_pki_int_max_ttl: "43800h"
vault_pki_int_ttl: "43800h"
vault_pki_int_local_path: "{{ vault_ssl_base_path }}/intermediate"
vault_pki_int_csr_file: "{{ vault_pki_int_local_path }}/{{ vault_pki_int_path }}.csr"
vault_pki_int_pem_file: "{{ vault_pki_int_local_path }}/{{ vault_pki_int_path }}.pem"
vault_pki_int_url_issue: "https://{{ vault_ssl_server_common_name }}:8200/v1/{{ vault_pki_int_path }}/ca"
vault_pki_int_url_crl: "http://{{ vault_ssl_server_common_name }}:8200/v1/{{ vault_pki_int_path }}/crl"
vault_pki_int_role_name: "inthepicture-dot-photo"
vault_pki_int_role_allowed_domains: "inthepicture.photo"
vault_pki_int_role_allow_subdomains: "true"
vault_pki_int_role_max_ttl: "72h"
vault_pki_int_openssl_days: "1825"
vault_pki_int_policy_file: "{{ vault_pki_int_local_path }}/intermediate-ca-policy.hcl"
vault_pki_int_policy_name: "pol-pki-int"
vault_pki_int_ca_share_filename: "InThePicture_Intermediate_CA_Chain.crt"
vault_pki_int_nomad_role: "nomad-cluster"
vault_pki_int_nomad_role_max_ttl: "8766h"

vault_snapshot_approle_path: "snapshot"
vault_snapshot_policy_name: "pol-snapshot"
vault_snapshot_token_name: "Token for snapshots"
vault_snapshot_token_local_path: "{{ bootstrap_location }}/snapshot.vault.token"

vault_snapshot_backup_main: "/srv/vault"
vault_snapshot_backup_location: "/srv/vault/backups"
vault_snapshot_backup_location_owner: "vault"
vault_snapshot_backup_location_group: "vault"
vault_snapshot_batchfile_template: "vault-snapshot.sh.j2"
vault_snapshot_batchfile_location: "/srv/vault/vault-snapshot.sh"
vault_snapshot_keep_days: "7"
vault_snapshot_filename: "vault"
vault_snapshot_file_extension: "snap"

vault_snapshot_cron_backup_minute: "00"
vault_snapshot_cron_backup_hour: "00"
