---

- name: Check if there is already a dnsmasq config.
  ansible.builtin.stat:
    path: "/etc/dnsmasq.d/10-consul"
  register: dnsmasq_consul_config

- name: dnsmasq configuration.
  block:

    - name: Ensure hosts file has correct entry for 127.0.1.1
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "127.0.1.1 "
        line: "127.0.1.1 {{ inventory_hostname }}"

    - name: Ensure dnsmasq is present.
      ansible.builtin.package:
        name: dnsmasq
        state: present

    - name: Ensure new default dnsmasq config is in place.
      ansible.builtin.template:
        src: dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        backup: true
        force: true
        mode: 0644
      notify: Restart dnsmasq

    - name: Ensure Consul dnsmasq config is in place.
      ansible.builtin.template:
        src: 10-consul.j2
        dest: /etc/dnsmasq.d/10-consul
        force: true
        mode: 0644
      notify: Restart dnsmasq

    - name: Ensure systemd-resolved is stopped.
      ansible.builtin.service:
        name: systemd-resolved
        state: stopped
        enabled: false

    - name: Ensure new resolv.conf file is present.
      ansible.builtin.template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf
        mode: 0644
        force: true

    - name: Ensure dnsmasq is started and enabled.
      ansible.builtin.service:
        name: dnsmasq
        state: started
        enabled: true

  when:
    - not dnsmasq_consul_config.stat.exists

