---
- name: Ensure Consul is excluded from the unattended upgrades.
  lineinfile:
    path: "/usr/share/unattended-upgrades/50unattended-upgrades"
    state: present
    line: '    "consul";'
    insertafter: 'Unattended-Upgrade::Package-Blacklist \{\n'
    backup: true
