---
- name: Ensure static configuration file
  ansible.builtin.template:
    src: traefik.toml.j2
    dest: /opt/traefikee/traefik.toml
    owner: "{{ traefikee_user_name }}"
    group: "{{ traefikee_group_name }}"
    mode: 0640

- name: Ensure systemd unit file
  ansible.builtin.copy:
    src: traefikee.service
    dest: /etc/systemd/system/traefikee.service
    mode: 0644

- name: Ensure systemd service
  ansible.builtin.systemd:
    daemon_reload: true
    service: traefikee.service
    state: started
    enabled: true

- name: Ensure Nomad jobs on management station
  ansible.builtin.template:
    src: "{{ item }}.nomad.j2"
    dest: "/home/{{ ansible_env.SUDO_USER }}/{{ item }}.nomad"
    mode: 0644
  delegate_to: localhost
  become: false
  with_items:
    - whoami
    - hashiflip-non-secure
    - hashiflip-secure
