---
- name: Common preparations
  hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: cryptography
      - name: docker
      - name: hvac
      - name: jmespath
      - name: python-nomad

  roles:
    - name: geerlingguy.pip
    - name: common
