---
- name: systemd-resolved
  hosts:
    - management
    - consul_servers
    - consul_clients
  become: true

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml

  roles:
    - name: systemd-resolved
