---
- name: Consul
  hosts:
    - consul_servers
    - consul_clients
  become: true

  vars:
    # Uncomment to override the encryption key if you are already running a working cluster.
    # consul_encryption_key: "gp7chR0aT5A5Zo9t7tiswOVrVktvRTD18bpLawGUOVM="

  roles:
    - name: hashicorp/consul

- name: Consul CA for desktop
  hosts:
    - desktop
  become: true

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml

  tasks:
    - name: Ensure Consul address
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_env.SUDO_USER }}/.bashrc"
        search_string: "CONSUL_HTTP_ADDR"
        line: "export CONSUL_HTTP_ADDR=https://consul.service.{{ consul_domain }}:8501"
      tags: bashrc

    - name: Ensure Consul CA in trust store
      delegate_to: consul1
      tags: consul-ca
      block:
        - name: Ensure the Consul CA certificate is transferred to the management station - Debian.
          ansible.posix.synchronize:
            src: "{{ consul_etc_directory }}/consul-agent-ca.pem"
            dest: "Consul_CA.pem"
          when: ansible_os_family == 'Debian'
          become: false

        - name: Ensure the Consul CA certificate is transferred to the management station - RedHat.
          ansible.posix.synchronize:
            src: "{{ consul_etc_directory }}/consul-agent-ca.pem"
            dest: "Consul_CA.pem"
          when: ansible_os_family == 'RedHat'
          become: false

    - name: Ensure Consul CA in trust store
      tags: consul-ca
      block:
        - name: Ensure the Consul CA certificate is copied to the local certs directory - Debian.
          ansible.builtin.copy:
            src: "/home/{{ ansible_env.SUDO_USER }}/Consul_CA.pem"
            dest: "/usr/local/share/ca-certificates/Consul_CA.pem"
            remote_src: true
            mode: 0644
          when: ansible_os_family == 'Debian'

        - name: Ensure the Consul CA certificate is copied to the local certs directory - RedHat.
          ansible.builtin.copy:
            src: "/home/{{ ansible_env.SUDO_USER }}/Consul_CA.pem"
            dest: "/etc/pki/ca-trust/source/anchors/Consul_CA.pem"
            remote_src: true
            mode: 0644
          when: ansible_os_family == 'RedHat'

        - name: Ensure certificate index is updated - Debian.
          ansible.builtin.command: "/usr/sbin/update-ca-certificates -f"
          when: ansible_os_family == 'Debian'

        - name: Ensure certificate index is updated - RedHat.
          ansible.builtin.command: "/usr/bin/update-ca-trust extract"
          when: ansible_os_family == 'RedHat'

    - name: Esnure cleanup of temp file
      ansible.builtin.file:
        path: "/home/{{ ansible_env.SUDO_USER }}/Consul_CA.pem"
        state: absent
      tags: consul-ca
