---
- name: Vault
  hosts:
    - vault_servers
    - vault_clients
    - nomad_servers
    - nomad_clients
  become: true

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml

  # Uncomment these lines if you want to unseal with other shards than present in the vault.master.keys file.
  # vars:
  #   vault_unseal_key_1: "xxxxxxxxxxx"
  #   vault_unseal_key_2: "yyyyyyyyyyy"
  #   vault_unseal_key_3: "zzzzzzzzzzz"

  roles:
    - name: hashicorp/vault

- name: Vault for desktop
  hosts: localhost
  connection: local
  become: false

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml

  tasks:
    - name: Ensure Vault address
      ansible.builtin.lineinfile:
        path: "/home/{{ ansible_env.HOME }}/.bashrc"
        search_string: "VAULT_ADDR"
        line: "export VAULT_ADDR=https://active.vault.service.{{ consul_domain }}:8200"
