---
- name: Nomad
  hosts:
    - nomad_servers
    - nomad_clients
  become: true

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml
    - ../roles/hashicorp/vault/vars/main.yml

  vars:
    # Uncomment var below and provide the right vault token if you are adding a new nomad client
    # nomad_server_vault_token: "xxxxxxx"

  roles:
    - name: hashicorp/nomad

- name: Nomad for desktop
  hosts: localhost
  connection: local
  become: false

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml

  tasks:
    - name: Ensure Nomad address
      ansible.builtin.lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        search_string: "NOMAD_ADDR"
        line: "export NOMAD_ADDR=https://nomad.service.{{ consul_domain }}:4646"
      tags: bashrc
