---
- name: Nomad
  hosts:
    - nomad_servers
    - nomad_clients
  become: true

  vars_files:
    - roles/hashicorp/consul/vars/main.yml
    - roles/hashicorp/vault/vars/main.yml

  vars:
    # Uncomment var below and provide the right vault token if you are adding a new nomad client
    # nomad_server_vault_token: "xxxxxxx"

  roles:
    - name: hashicorp/nomad
