---
- name: Bonus
  hosts: localhost
  become: false
  gather_facts: false

  vars_files:
    - ../roles/hashicorp/consul/vars/main.yml
    - ../roles/hashicorp/vault/vars/main.yml
    - ../roles/hashicorp/nomad/vars/main.yml

  vars:
    consul_address: https://consul.service.inthepicture.photo:8501
    vault_address: https://vault.service.inthepicture.photo:8200
    nomad_address: https://nomad.service.inthepicture.photo:4646

  tasks:
    - name: Create fact of admin password.
      ansible.builtin.set_fact:
        admin_password: "{{ lookup('file', vault_admin_local_path) }}"

    - name: Retrieve client token.
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/auth/userpass/login/{{ vault_admin_username }}"
        method: POST
        body_format: json
        body: '{ "password": "{{ admin_password }}" }'
        status_code:
          - 200
          - 204
        validate_certs: false
      register: vault_admin_login_response

    - name: Set fact of client token.
      ansible.builtin.set_fact:
        admin_token: "{{ vault_admin_login_response.json.auth.client_token }}"

    - name: Ensure Consul secrets engine
      ansible.builtin.uri:
        url: "{{ vault_address }}/v1/auth/userpass/login/{{ vault_admin_username }}"
        method: POST
        body_format: json
        body: '{ "password": "{{ admin_password }}" }'
        status_code:
          - 200
          - 204
        validate_certs: false
