---
- name: Waypoint
  hosts:
    - desktop
    - nomad_clients
  become: true

  vars_files:
    - ../roles/hashicorp/nomad/vars/main.yml

  vars:
    nomad_consul_address: "https://nomad.service.inthepicture.photo:4646"

  roles:
    - name: chrisvanmeer.hashicorp
      vars:
        hashicorp_product_selection:
          - waypoint
      when: ansible_hostname == "desktop"

  tasks:
    - name: Retrieve Nomad token # noqa run_once[task]
      ansible.builtin.command: "awk '/Secret ID/ {print $4}' {{ nomad_bootstrap_token_local_path }}"
      changed_when: false
      become: false
      register: nomad_token
      delegate_to: localhost
      run_once: true

    - name: Ensure host volumes on disk
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ nomad_data_directory_owner }}"
        group: "{{ nomad_data_directory_group }}"
        mode: 0755
      loop:
        - "{{ nomad_waypoint_server_volume_full_path }}"
        - "{{ nomad_waypoint_runner_volume_full_path }}"
      when: ansible_hostname in groups["nomad_clients"]

    - name: Ensure host volume configuration
      ansible.builtin.template:
        src: client.hcl.j2
        dest: "{{ nomad_etc_directory }}/client.hcl"
        mode: 0600
      vars:
        waypoint_config: true
      notify:
        - Restart Nomad
        - Pause
      when: ansible_hostname in groups["nomad_clients"]

    - name: Flush handlers
      ansible.builtin.meta: flush_handlers

    - name: Ensure waypoint installation # noqa run_once[task]
      ansible.builtin.command:
        cmd: "waypoint install -platform=nomad -accept-tos -nomad-host-volume={{ nomad_waypoint_server_volume }} -nomad-runner-host-volume={{ nomad_waypoint_runner_volume }}"
      environment:
        NOMAD_TOKEN: "{{ nomad_token.stdout }}"
        NOMAD_ADDR: "{{ nomad_consul_address }}"
      register: waypoint_install_results
      delegate_to: localhost
      changed_when: false
      run_once: true

    - name: Output installation details # noqa run_once[task]
      ansible.builtin.debug:
        var: waypoint_install_results
      when: waypoint_install_results is defined
      delegate_to: localhost
      run_once: true

  handlers:
    - name: Restart Nomad
      ansible.builtin.service:
        name: nomad
        state: restarted
    - name: Pause
      ansible.builtin.pause:
        seconds: 5
