---
- name: Reset Traefik
  hosts:
    - traefik2
  become: true

  vars_files:
    - ../roles/traefik/default/main.yml

  tasks:
    - name: Management station
      delegate_to: localhost
      run_once: true  # noqa: run-once[task]
      block:
        - name: Remove management station files.
          ansible.builtin.file:
            path: "{{ item }}"
            state: absent
          with_items:
            - "/home/{{ ansible_env.SUDO_USER }}/hashiflip.nomad"
            - "/home/{{ ansible_env.SUDO_USER }}/whoami.nomad"
          delegate_to: localhost
          ignore_errors: true  # noqa: ignore-errors

    - name: Stop service
      ansible.builtin.systemd:
        service: traefik.service
        state: stopped
        enabled: false
      ignore_errors: true  # noqa: ignore-errors

    - name: Remove systemd unit file
      ansible.builtin.file:
        dest: /etc/systemd/system/traefik.service
        state: absent
      ignore_errors: true  # noqa: ignore-errors

    - name: Remove directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ traefik_base_dir }}"
        - "{{ traefik_log_dir }}"
      ignore_errors: true  # noqa: ignore-errors

    - name: Remove traefik group
      ansible.builtin.group:
        name: "{{ traefik_group_name }}"
        state: present
      ignore_errors: true  # noqa: ignore-errors

    - name: Remove traefik user
      ansible.builtin.user:
        name: "{{ traefik_user_name }}"
        state: present
      ignore_errors: true  # noqa: ignore-errors

    - name: Remove binary
      ansible.builtin.file:
        path: /usr/local/bin/traefik
        state: absent
      ignore_errors: true  # noqa: ignore-errors
